# Generated by Django 4.1.7 on 2023-03-05 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_task',
            name='room',
        ),
    ]
